version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/data/postgresql
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  data:
    driver: local